apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-frontend-dev
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: node-mongo-app
        tier: backend
        track: stable
        env: dev
        role: frontend
    spec:
      containers:
        - name: "node-mongo"
          image: "gcr.io/cloud-solutions-images/node-mongo:v1"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "DB_PORT"
              value: "27017"
            - name: "DB_HOST"
              value: "mongo"