apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-frontend-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-mongo-app
        tier: frontend
        track: stable
        env: dev
        role: frontend
    spec:
      containers:
        - name: "node-mongo"
          image: "gcr.io/extreme-torch-190915/app:master.1"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: "SERVER_PORT"
              value: "8080"
            - name: "DB_PORT"
              value: "27017"
            - name: "DB_HOST"
              value: "app-db"