apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-mongo-app
        tier: db
        track: stable
    spec:
      containers:
        - name: mongo
          image: "mongo"
          # volumeMounts:
          #   - mountPath: /data/db
          #     name: db-volume
          ports:
            - name: http
              containerPort: 27017
      # volumes:
      #   - name: db-volume
      #     hostPath:
      #       # directory location on host
      #       path: /mongo/db